export enum ErrorCode {
    // HTTP Status Codes
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    INTERNAL_SERVER = 500,
    SERVICE_UNAVAILABLE = 503,

    // Common Error Codes
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
    BUSINESS_ERROR = 'BUSINESS_ERROR',
    TECHNICAL_ERROR = 'TECHNICAL_ERROR',
    DB_ERROR = 'DB_ERROR',

    // Auth Error Codes
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',

    // Database Error Codes
    DB_CONNECTION_ERROR = 'DB_CONNECTION_ERROR',
    DB_QUERY_ERROR = 'DB_QUERY_ERROR',
    DB_DUPLICATE_KEY = 'DB_DUPLICATE_KEY',

    // Process Error Codes
    PROCESS_NOT_FOUND = 'PROCESS_NOT_FOUND',
    PROCESS_ALREADY_EXISTS = 'PROCESS_ALREADY_EXISTS',
    PROCESS_INVALID_STATUS = 'PROCESS_INVALID_STATUS',
    PROCESS_CREATION_FAILED = 'PROCESS_CREATION_FAILED',
    PROCESS_UPDATE_FAILED = 'PROCESS_UPDATE_FAILED',
    PROCESS_DELETE_FAILED = 'PROCESS_DELETE_FAILED',

    // Engine Error Codes
    ENGINE_START_ERROR = 'ENGINE_START_ERROR',
    ENGINE_STOP_ERROR = 'ENGINE_STOP_ERROR',
    ENGINE_STATE_ERROR = 'ENGINE_STATE_ERROR'

} 